# Ejercicio 1
Crea un arreglo de dos dimensiones de tamaño 3x3, con elementos aleatorios de numeros del 0 al 100.

In [19]:
import numpy as np

"""
V - Matriz de ejemplo - V
Matriz: list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
"""

Matriz = np.random.randint(100, size=(3, 3))

In [20]:
# Resultado matriz

print( Matriz )

[[24 53 38]
 [ 6 81 83]
 [37 78 60]]


# Ejercicio 2
Utilice las siguientes funciones en el arreglo creado en el punto 1
- Promedio de los elementos
- Suma de los elementos
- Mostrar el elemento mayor
- Mostrar el elemento menor
- Mostrar solo los elementos de la diagonal principal

In [21]:
# El valor Matriz esta especificado en el Ejercicio 1

print( np.average(Matriz) )
print( np.sum(Matriz) )
print( np.max(Matriz) )
print( np.min(Matriz) )
print( np.diagonal( Matriz ) )

51.111111111111114
460
83
6
[24 81 60]


# Ejercicio 3
Crear un arreglo de dos dimensiones de 3x3 con numeros ceros, excepto la diagonal principal que debe contener en el mismo orden los siguientes elementos 1, 2 y 3

In [22]:
Arreglo: list = np.array([1, 1, 1])

MatrizBinaria: list = np.diag(Arreglo)

print(MatrizBinaria)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
